// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf83Y46bEPGSHUDtYsuTtnFnKvg8pKKqg',
    appId: '1:791460811551:web:77657dc7db4091fa3f162a',
    messagingSenderId: '791460811551',
    projectId: 'agora-calling-app-c9257',
    authDomain: 'agora-calling-app-c9257.firebaseapp.com',
    storageBucket: 'agora-calling-app-c9257.firebasestorage.app',
    measurementId: 'G-08E5YR37KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA71P_q6j4DBfm00Wl0b2J3dOR4aRaD-a8',
    appId: '1:791460811551:android:4a89644ac78788353f162a',
    messagingSenderId: '791460811551',
    projectId: 'agora-calling-app-c9257',
    storageBucket: 'agora-calling-app-c9257.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXF-v6FS3lXt83Fup5BgjGX9gQJGu-ntY',
    appId: '1:791460811551:ios:838c85cb6619af553f162a',
    messagingSenderId: '791460811551',
    projectId: 'agora-calling-app-c9257',
    storageBucket: 'agora-calling-app-c9257.firebasestorage.app',
    iosBundleId: 'com.example.agoraCallingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXF-v6FS3lXt83Fup5BgjGX9gQJGu-ntY',
    appId: '1:791460811551:ios:838c85cb6619af553f162a',
    messagingSenderId: '791460811551',
    projectId: 'agora-calling-app-c9257',
    storageBucket: 'agora-calling-app-c9257.firebasestorage.app',
    iosBundleId: 'com.example.agoraCallingApp',
  );
}
